name: 'Repository Creation Bot'
description: 'A bot for creating repositories in a GitHub Organization through Issues and GitHub Actions.'
author: 'Daniel Kuschny'
inputs:
  api_url:
    required: false
    description: 'The URL of the API to use, required for GHES.'
  org_admins:
    required: true
    description: 'The name of the team which will be pinged if admin level approval is needed.'
  token:
    required: true
    description: 'A personal access token which has access to all repos as admin and can create new repos. Will be used for all API interactions to create the repository and comment on the issues.'
runs:
  using: 'node16'
  main: 'dist/index.js'